apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: store-icons
  description: Store Icons are sets of icons tailored for store UI
  tags:
    - javascript
  annotations:
    vtex.com/janus-acronym: ""
    vtex.com/o11y-os-index: ""
    grafana/dashboard-selector: ""
    github.com/project-slug: vtex-apps/store-icons
    vtex.com/platform-flow-id: ""
    backstage.io/techdocs-ref: dir:../
    vtex.com/application-id: USEVZVXD
spec:
  lifecycle: stable
  owner: te-0013
  type: frontend-ui
  dependsOn: []
